### ISSUE TITLE
IllegalStateException: Not allowed to start service Intent (Android O)

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-events-android#129]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/901

```
 Process: ro.ascendnet.android.startaxi.taximetrist, PID: 4001
                                                                                         java.lang.ExceptionInInitializerError
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30)
                                                                                             at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49)
                                                                                             at ro.ascendnet.android.startaxi.taximetrist.core.Driver.onCreate(Driver.java:34)
                                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747)
                                                                                             at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6501)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                          Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ro.ascendnet.android.startaxi.taximetrist/com.mapbox.android.telemetry.TelemetryService }: app is in background uid UidRecord{4f69d22 u0a197 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
                                                                                             at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
                                                                                             at android.app.ContextImpl.startService(ContextImpl.java:1477)
                                                                                             at android.content.ContextWrapper.startService(ContextWrapper.java:650)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.startLocation(MapboxTelemetry.java:490)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetryService(MapboxTelemetry.java:226)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.optLocationIn(MapboxTelemetry.java:197)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry(MapboxTelemetry.java:461)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.enable(MapboxTelemetry.java:136)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:25)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:10)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.<clinit>(Telemetry.java:42)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41) 
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46) 
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30) 
                                                                                             at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49) 
                                                                                             at ro.ascendnet.android.startaxi.taximetrist.core.Driver.onCreate(Driver.java:34) 
                                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120) 
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747) 
                                                                                             at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                             at android.os.Looper.loop(Looper.java:164) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6501) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                                             at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

That's because the new Android O background execution limits on API 26+ 👀 

https://developer.android.com/about/versions/oreo/android-8.0-changes#back-all

More in depth reference 👉 https://developer.android.com/about/versions/oreo/background.html

@vladgheorghe we're working on bringing the changes needed in https://github.com/mapbox/mapbox-events-android/pull/70 in the meantime, I guess a workaround would be to target/compile with API 25 instead. BTW, do you have some more information on used device and Android version?

cc @electrostat @zugaldia

**Comment by electrostat** [comment]
@vladgheorghe I'm having a hard time replicating this crash for testing purposes. Could you provide more info? Looking for sdk and version you're using, build config of your app, and any unique implementation you could be using. Hoping to get this fix in our next release. Thanks.

**Comment by vladgheorghe** [comment]
Hello, I am sorry if I am slow to respond, I am working on multiple projects and also travelling quite a bit. I can confirm that I’ve randomly reproduced this crash on Oreo, navi 0.13snapshot 2 commits ago with location 0.5.0 release and maps sdk 6.0.1. My most recent build is with the latest snapshot version, sdk 6.0.1 and location layer 0.6.0 snapshot. No crashes so far even on oreo but I have rolled out the app to our testers and I will come back with more info as soon as I have anything.

**Comment by vladgheorghe** [comment]
I think I might have some possible STRs for this issue, altough I'm fairly certain that It crashes in other scenarios as well:

open a Mapbox Activity (mapview, navi, llp, implemented as per docs)
start ActivityForResult to another activity
return with result
force close app process

Somewhere along these lines always crashes for me after force closing. 

```
FATAL EXCEPTION: main
                                                                                         Process: ro.ascendnet.android.startaxi.taximetrist, PID: 3855
                                                                                         java.lang.ExceptionInInitializerError
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30)
                                                                                             at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49)
                                                                                             at ro.ascendnet.android.startaxi.taximetrist.core.Driver.onCreate(Driver.java:34)
                                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747)
                                                                                             at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6501)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                          Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ro.ascendnet.android.startaxi.taximetrist/com.mapbox.android.telemetry.TelemetryService }: app is in background uid UidRecord{17dc860 u0a207 SVC  idle change:uncached procs:1 seq(0,0,0)}
                                                                                             at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
                                                                                             at android.app.ContextImpl.startService(ContextImpl.java:1477)
                                                                                             at android.content.ContextWrapper.startService(ContextWrapper.java:650)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.startLocation(MapboxTelemetry.java:490)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetryService(MapboxTelemetry.java:226)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.optLocationIn(MapboxTelemetry.java:197)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry(MapboxTelemetry.java:461)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.enable(MapboxTelemetry.java:136)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:25)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:10)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.<clinit>(Telemetry.java:42)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41) 
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46) 
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30) 
                                                                                             at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49) 
                                                                                             at ro.ascendnet.android.startaxi.taximetrist.core.Driver.onCreate(Driver.java:34) 
                                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120) 
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747) 
                                                                                             at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                             at android.os.Looper.loop(Looper.java:164) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6501) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                                             at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by vladgheorghe** [comment]
Also, I'm getting these logs before that crash

```

05-04 21:37:13.085 6188-6188/ro.ascendnet.android.startaxi.taximetrist E/BpSurfaceComposerClient: Failed to transact (-1)
05-04 21:37:13.086 6188-6188/ro.ascendnet.android.startaxi.taximetrist E/BpSurfaceComposerClient: Failed to transact (-1)
```

**Comment by vladgheorghe** [comment]
Currently using navi 0.13 release, maps sdk 6.0.1 and LLP 0.6.0-snapshot

**Comment by DejanRistic** [comment]
@electrostat I saw a similar error happen when migrating things over to 6+ and events. Posting a crash report here in case it helps! 

http://crashes.to/s/1026f220067

**Comment by jplipata** [comment]
Our app has this crash showing in Crashlytics as well

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41)
       at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46)
       at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30)
       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49)
       at com.mydomain.myapp.MyApp.onCreate(MyApp.java:86)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056)
       at android.app.ActivityThread.-wrap1(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

And 

```
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.mydomain.myapp/com.mapbox.android.telemetry.TelemetryService }: app is in background uid UidRecord{5b4c0b9 u0a209 CEM  idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at com.mapbox.android.telemetry.MapboxTelemetry.startLocation(MapboxTelemetry.java:492)
       at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetryService(MapboxTelemetry.java:228)
       at com.mapbox.android.telemetry.MapboxTelemetry.optLocationIn(MapboxTelemetry.java:199)
       at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry(MapboxTelemetry.java:463)
       at com.mapbox.android.telemetry.MapboxTelemetry.enable(MapboxTelemetry.java:137)
       at com.mapbox.mapboxsdk.maps.Telemetry.(Telemetry.java:25)
       at com.mapbox.mapboxsdk.maps.Telemetry.(Telemetry.java:10)
       at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.(Telemetry.java:42)
       at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41)
       at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46)
       at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30)
       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49)
       at com.mydomain.myapp.MyApp.onCreate(MyApp.java:86)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056)
       at android.app.ActivityThread.-wrap1(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by electrostat** [comment]
@DejanRistic @jplipata  I am working on a fix for this Oreo issue and we are doing a future release to address it, combined with unique updates related directly to Oreo.

**Comment by jplipata** [comment]
@electrostat ok great news. Thanks!  Do you have an ETA for the release?

**Comment by sictiru** [comment]
I subscribe to the fix for Oreo+

**Comment by JoelNieman** [comment]
Any update on when we can expect this fix to be available?

**Comment by electrostat** [comment]
PR https://github.com/mapbox/mapbox-events-android/pull/157 has landed, which fixes this bug. Closing issue. Reopen and advise if still an issue.

**Comment by KaviPaviTwins** [comment]
Can you share the updated code for the telementary issue in mapbox.

**Comment by zugaldia** [comment]
@KaviPaviTwins this fix went out with v3.1.3 of the telemetry library and should be available in the latest version of the Mapbox Maps SDK. Please let us know if you still see the issue after upgrading.

**Comment by goswamiji0** [comment]
I'm facing this issue in my Oreo Samsung A7 Phone. Anyone have a solution then let me know.

W/System.err: java.lang.IllegalStateException: Not allowed to start service Intent

**Comment by andrlee** [comment]
hey @goswamiji0 thanks for reporting this. the solution is to upgrade to https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v7.3.2 where `TelemetryService` is    replaced with new collector rebuilt from ground up. Please follow this migration guide: https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide.
