### ISSUE TITLE
Telemetry crash on stop service

### ISSUE THREAD

**Issue by AlexeyIke** [mapbox/mapbox-events-android#145]
Hello,
i've use mapbox sdk v 6.0.1 + telemetry 3.0.2 + location layer plugin 0.5.0
Has very rare crash on fabric stat: 
xiaomi, oneplus, android 6.0.1,   100%   App In Background 

Fatal Exception: java.lang.RuntimeException: Unable to stop service com.mapbox.android.telemetry.TelemetryService@eba3f54: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.android.telemetry.TelemetryLocationEnabler$LocationState com.mapbox.android.telemetry.TelemetryLocationEnabler.updateTelemetryLocationState(com.mapbox.android.telemetry.TelemetryLocationEnabler$LocationState)' on a null object reference
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3105)
       at android.app.ActivityThread.access$2400(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
       at android.os.Handler.dispatchMessage(Handler.java:102)
+
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.android.telemetry.TelemetryLocationEnabler$LocationState com.mapbox.android.telemetry.TelemetryLocationEnabler.updateTelemetryLocationState(com.mapbox.android.telemetry.TelemetryLocationEnabler$LocationState)' on a null object reference
       at com.mapbox.android.telemetry.TelemetryService.disableTelemetryLocationState(TelemetryService.java:240)
       at com.mapbox.android.telemetry.TelemetryService.onDestroy(TelemetryService.java:64)
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3082)
       at android.app.ActivityThread.access$2400(ActivityThread.java:154)

New SDK 6.1.1 + telemetry 3.1.0 + locationLayer 0.5.2  can fix this issue?

**Comment by Guardiola31337** [comment]
Hey @AlexeyIke 👋 thanks for reaching out and report your issue.

I'm going to close here in favor of https://github.com/mapbox/mapbox-events-android/issues/147
Please, could you add some more information for reproducing the crash (minimal example) or any other specifics around your test setup and some information on used device there? If there is any sample or pseudo code you can provide, that would be also really helpful.

Thanks again!

**Comment by AlexeyIke** [comment]
Hello, it crash from fabric and i've not has a phone with 6.0.1 to test it. I've try on latest sdk /telemetry versions and alert if crash happen again.
