### ISSUE TITLE
Issues when requesting Location with Engine

### ISSUE THREAD

**Issue by Atternatt** [mapbox/mapbox-events-android#169]
Calling `requestLocationUpdates()` makes the app crash.

**dependencies:**
`implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.3"`
`implementation "com.mapbox.mapboxsdk:mapbox-android-core:0.2.0"`
`implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.0'`
`implementation 'com.google.android.gms:play-services-base:15.0.1'`
`implementation('com.google.android.gms:play-services-location:15.0.1')`

**The code:**
`//calling it in a fragment`
`private val locationEngine: LocationEngine by lazy { LocationEngineProvider(context).obtainBestLocationEngineAvailable() }`

```
override fun onStart() {
        requestPermission(android.Manifest.permission.ACCESS_FINE_LOCATION) {
            locationEngine.apply {
                if (it) { //has permission
                    activate()
                    addLocationEngineListener(object : LocationEngineListener {
                        override fun onLocationChanged(location: Location) {
                            Log.i("New Position", "${location.latitude} ${location.longitude}")
                        }

                        @SuppressLint("MissingPermission")
                        override fun onConnected() {
                            requestLocationUpdates() //crashes here
                        }

                    })

                }
            }
        }
        super.onStart()
    }
```

**crash log:**
```
2018-06-19 12:09:09.530 4351-4351/com.m2f.tagn.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.m2f.tagn.debug, PID: 4351
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapbox.android.core.location.UpdateGoogleRequestPriority.update(com.google.android.gms.location.LocationRequest)' on a null object reference
        at com.mapbox.android.core.location.GoogleLocationEngine.updateRequestPriority(GoogleLocationEngine.java:167)
        at com.mapbox.android.core.location.GoogleLocationEngine.requestLocationUpdates(GoogleLocationEngine.java:129)
        at com.m2f.tagn.map.MapFragment$onStart$1$1$1.onConnected(MapFragment.kt:115)
        at com.mapbox.android.core.location.GoogleLocationEngine.onConnected(GoogleLocationEngine.java:93)
        at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess(Unknown Source:109)
        at com.google.android.gms.common.api.internal.zzav.zzb(Unknown Source:22)
        at com.google.android.gms.common.api.internal.zzaj.zzat(Unknown Source:92)
        at com.google.android.gms.common.api.internal.zzaj.onConnected(Unknown Source:21)
        at com.google.android.gms.common.api.internal.zzbd.onConnected(Unknown Source:7)
        at com.google.android.gms.common.api.internal.zzp.onConnected(Unknown Source:5)
        at com.google.android.gms.common.internal.zzf.onConnected(Unknown Source:2)
        at com.google.android.gms.common.internal.BaseGmsClient$PostInitCallback.handleServiceSuccess(Unknown Source:130)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:62)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:2)
        at com.google.android.gms.common.internal.BaseGmsClient$CallbackProxy.deliverCallback(Unknown Source:51)
        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:270)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2018-06-19 12:09:09.532 4351-4351/com.m2f.tagn.debug E/UncaughtException: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapbox.android.core.location.UpdateGoogleRequestPriority.update(com.google.android.gms.location.LocationRequest)' on a null object reference
        at com.mapbox.android.core.location.GoogleLocationEngine.updateRequestPriority(GoogleLocationEngine.java:167)
        at com.mapbox.android.core.location.GoogleLocationEngine.requestLocationUpdates(GoogleLocationEngine.java:129)
        at com.m2f.tagn.map.MapFragment$onStart$1$1$1.onConnected(MapFragment.kt:115)
        at com.mapbox.android.core.location.GoogleLocationEngine.onConnected(GoogleLocationEngine.java:93)
        at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess(Unknown Source:109)
        at com.google.android.gms.common.api.internal.zzav.zzb(Unknown Source:22)
        at com.google.android.gms.common.api.internal.zzaj.zzat(Unknown Source:92)
        at com.google.android.gms.common.api.internal.zzaj.onConnected(Unknown Source:21)
        at com.google.android.gms.common.api.internal.zzbd.onConnected(Unknown Source:7)
        at com.google.android.gms.common.api.internal.zzp.onConnected(Unknown Source:5)
        at com.google.android.gms.common.internal.zzf.onConnected(Unknown Source:2)
        at com.google.android.gms.common.internal.BaseGmsClient$PostInitCallback.handleServiceSuccess(Unknown Source:130)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:62)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:2)
        at com.google.android.gms.common.internal.BaseGmsClient$CallbackProxy.deliverCallback(Unknown Source:51)
        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:270)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
   
**device:** 
Emulator Nexus 5X API 26 with Play Store, Target Ansdroid 8.0 (Google Play)

**Comment by electrostat** [comment]
@Atternatt Did some digging and figured out the problem. You are not setting the priority  for the location engine. Something like `locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY)` before you `activate` the engine will solve your problem.  You can use any of the priority levels we offer.

I will work on a solution for when a developer does not set a priority to prevent this crash in the future. Thanks for finding it.
