### ISSUE TITLE
ConcurrentQueue NoSuchElementException race condition

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-events-android#342]
Run into a weird 💥 when testing:

```
Fatal Exception: java.util.NoSuchElementException
       at java.util.AbstractQueue.remove(AbstractQueue.java:117)
       at com.mapbox.android.telemetry.ConcurrentQueue.flush(ConcurrentQueue.java:26)
       at com.mapbox.android.telemetry.FullQueueFlusher.onFullQueueFlush(FullQueueFlusher.java:15)
       at com.mapbox.android.telemetry.EventsQueue.push(EventsQueue.java:22)
       at com.mapbox.android.telemetry.MapboxTelemetry.pushToQueue(MapboxTelemetry.java:423)
       at com.mapbox.android.telemetry.MapboxTelemetry.push(MapboxTelemetry.java:126)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationMetricsWrapper.push(NavigationMetricsWrapper.java:63)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry$1.run(NavigationTelemetry.java:556)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)
```

Galaxy S7
Android `8.0.0`

Apparently we're incrementing the `count` even if the `queue.add` call is not successful 👀 https://github.com/mapbox/mapbox-events-android/blob/036d95cd6adde056adfe742ff8cc1317242b5daf/libtelemetry/src/main/java/com/mapbox/android/telemetry/ConcurrentQueue.java#L17-L21 which causes the `NoSuchElementException` because it loops through `count` when trying to `flush` / `remove` https://github.com/mapbox/mapbox-events-android/blob/036d95cd6adde056adfe742ff8cc1317242b5daf/libtelemetry/src/main/java/com/mapbox/android/telemetry/ConcurrentQueue.java#L23-L31 when that event wasn't actually added to the queue.

This is rare but we should definitely account for it.

cc @kevinkreiser

**Comment by andrlee** [comment]
@Guardiola31337 thanks for spending time to dig into it! i'll push the fix for it today, any particular release/deliverable is blocked by it? 

/cc @mapbox/mobile-telemetry

**Comment by andrlee** [comment]
Fixed with https://github.com/mapbox/mapbox-events-android/pull/344

**Comment by Chaoba** [comment]
@chriswu42 @m-stephen
