### ISSUE TITLE
Last location unavailable crash

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-events-android#374]
Bit of weird crash:

```
    java.lang.Exception: Last location unavailable
        at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:40)
        at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
        at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1315)
        at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1134)
        at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1248)
        at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:502)
        at com.mapbox.mapboxsdk.activity.MainActivity.activateLocationComponent(MainActivity.java:97)
        at com.mapbox.mapboxsdk.activity.MainActivity.access$200(MainActivity.java:22)
        at com.mapbox.mapboxsdk.activity.MainActivity$3.onStyleLoaded(MainActivity.java:82)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:845)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:205)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1178)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:194)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1031)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:128)
        at android.os.Looper.loop(Looper.java:151)
        at android.app.ActivityThread.main(ActivityThread.java:5371)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
        at dalvik.system.NativeStart.main(Native Method)
```

When doing:

```
    implementation (project(':MapboxGLAndroidSDK')) {
        exclude group: 'com.android.support', module: 'support-compat'
        exclude group: 'com.android.support', module: 'support-fragment'
    }
```

and trying to show a location component on the map. 

Works well when not having the excluding `'support-compat'` declared.

**Comment by Chaoba** [comment]
@tobrun I have tested all location related examples in Android sdk test App on master branch, but can't reproduce this issue. The classes in support-compat have nothing related with location, so maybe it is some thing else cause the issue, like location permission etc.

**Comment by tobrun** [comment]
If it's not reproducible anymore, let's just close it for now. thank you for taking a look!

**Comment by hollandkyle** [comment]
I am encountering this error when mapbox is initialized in one location, then the device is turned off, then the device is turned and mapbox is initialized in a new location that is far away from the old location.  For example, this happens when I'm developing in Minneapolis, turn off the device and travel to San Francisco, then turn the device back on.  Here is the stack trace:

E/Mbgl-LocationComponent: Failed to obtain last location update
    java.lang.Exception: Last location unavailable
        at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:40)
        at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
        at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1354)
        at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1173)
        at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1287)
        at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:506)
        at org.forestcarbonworks.oxylus.presenter.flow.step.LocationStep.onBaseMapLoadComplete(LocationStep.java:166)
        at org.forestcarbonworks.oxylus.view.fragment.MapFragment$2$1.onStyleLoaded(MapFragment.java:185)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:855)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:212)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1264)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1035)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)

-------------------------------

And here (---->) is the line throwing the error:

// Get an instance of the component
            LocationComponent locationComponent = mapboxMap.getLocationComponent();

            // Activate with a built LocationComponentActivationOptions object
            locationComponent.activateLocationComponent(LocationComponentActivationOptions.builder(mFragment.getContext(), style).build());

            // Enable to make component visible
            locationComponent.setLocationComponentEnabled(true);

            // Set the component's camera mode
            locationComponent.setCameraMode(CameraMode.TRACKING);

            // Set the component's render mode
            locationComponent.setRenderMode(RenderMode.COMPASS);

            locationComponent.zoomWhileTracking(16, 2000);

            mLocationEngine = locationComponent.getLocationEngine();

            mLocationEngine.getLastLocation(this);

            LocationEngineRequest request = new LocationEngineRequest.Builder(UPDATE_INTERVAL_IN_MILLISECONDS)
                    .setPriority(LocationEngineRequest.PRIORITY_HIGH_ACCURACY)
                    .setMaxWaitTime(UPDATE_MAX_WAIT_TIME).build();

            ----->  mLocationEngine.requestLocationUpdates(request, this, null);

**Comment by hollandkyle** [comment]
Sorry, wrong line...  ...here is the line

// Activate with a built LocationComponentActivationOptions object
        locationComponent.activateLocationComponent(LocationComponentActivationOptions.builder(mFragment.getContext(), style).build());

        // Enable to make component visible
        --------> locationComponent.setLocationComponentEnabled(true);

        // Set the component's camera mode
        locationComponent.setCameraMode(CameraMode.TRACKING);

        // Set the component's render mode
        locationComponent.setRenderMode(RenderMode.COMPASS);

        locationComponent.zoomWhileTracking(16, 2000);

        mLocationEngine = locationComponent.getLocationEngine();

        mLocationEngine.getLastLocation(this);

        LocationEngineRequest request = new LocationEngineRequest.Builder(UPDATE_INTERVAL_IN_MILLISECONDS)
                .setPriority(LocationEngineRequest.PRIORITY_HIGH_ACCURACY)
                .setMaxWaitTime(UPDATE_MAX_WAIT_TIME).build();

        mLocationEngine.requestLocationUpdates(request, this, null);

**Comment by Chaoba** [comment]
@hollandkyle Have you checked the location permission before?

**Comment by hollandkyle** [comment]
Yes, all location permissions have been checked.  This issue only occurs
when the activity is terminated in one location and then the activity is
recreated in at a different location that is very far away from the first
location.

**Comment by william-reed** [comment]
experiencing the same issue after an emulator cold boot

**Comment by Chaoba** [comment]
@hollandkyle According to [android doc ](https://developer.android.com/reference/android/location/LocationManager.html#getLastKnownLocation(java.lang.String)), `getLastKnowLocation` can return null and your stack trace is printed by [LocationComponent](https://github.com/mapbox/mapbox-gl-native/blob/b6dd995813625a89bba8937c512cdf1175827d66/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java#L1496) which is by design.It could be easily triggered by closing location service in your phone. So IMHO I don't think it is an issue unless it causes crash.

**Comment by hollandkyle** [comment]
@Chaoba upon error, the location service is running and location updates are being handled correctly.  This issue causes a crash in this very specific case, so my present workaround is to catch the error thrown by setLocationComponentEnabled(true) and proceed without location updates until the device somehow locates itself at a later time.  As I describe earlier, there are narrow conditions that cause this crash otherwise location updates are as expected.

**Comment by Chaoba** [comment]
@hollandkyle Can you confirm it will cause crash? I try to reproduce this issue by closing location service and it will print the following log with crash.
```
2019-07-30 10:29:13.889 7776-7776/com.mapbox.mapboxsdk.testapp E/Mbgl-LocationComponent: Failed to obtain last location update
    java.lang.Exception: Last location unavailable
        at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:40)
        at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
        at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1354)
        at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1173)
        at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1287)
        at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:506)
        at com.mapbox.mapboxsdk.testapp.activity.location.LocationFragmentActivity$LocationFragment$onViewCreated$1$1.onStyleLoaded(LocationFragmentActivity.kt:112)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:855)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:212)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1264)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1035)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:7015)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
```
