### ISSUE TITLE
Last Location Unavailable

### ISSUE THREAD

**Issue by william-reed** [mapbox/mapbox-events-android#419]
**Configuration**
 - SDK Version: mapbox 7.3.0
 - Android OS Version 25 and 28 tested
 - Device model(s): emulator and galaxy tab e 8

**Steps to Reproduce**
Cold boot my emulator and try and obtain location with. **This only occurs right after a reboot.** I am wondering what this might have to do with https://stackoverflow.com/a/16866830/1572848
```
val locationEngine = LocationEngineProvider.getBestLocationEngine(getApplication())
try {
    locationEngine.getLastLocation(object : LocationEngineCallback<LocationEngineResult?> {
        override fun onSuccess(result: LocationEngineResult?) {
            // ... 
        }

        override fun onFailure(exception: Exception) {
            // ...
        }
    })
```

**Expected**
What did you expect?
To receive a location. If not possible on the first attempt is there another API exposed by mapbox to have a callback when location is available? Or would I have to revert to Google's API's for that.

**Logging**
Please attach logs or error messages

```
com.my.app E/DriverNavViewModel$onNavigationReady: java.lang.Exception: Last location unavailable
        at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:40)
        at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
        ...
        at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:225)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:855)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:212)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1264)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1035)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Also wondering if this has to do with #374 and #396

**Comment by alfwatt** [comment]
@andrlee not sure how `LocationEngineProvider` is supposed to work in the simulator, is this expected?

**Comment by andrlee** [comment]
@alfwatt we're pretty much adhering to google apis behavior with the only diff: if last location isn't available in google they return `null` and we throw an exception. Perhaps we need to document api signature to set expectation.

**Comment by alfwatt** [comment]
Assigned: Valid: https://github.com/mapbox/mobile-telemetry/issues/458

**Comment by nkukday** [comment]
[Docs](https://docs.mapbox.com/android/core/overview/#requesting-location-updates)
Consider using `requestLocationUpdates` instead of `getLastLocation`. Hope this helps!
