### ISSUE TITLE
Mapbox: Failed to obtain last location update

### ISSUE THREAD

**Issue by iamalminko** [mapbox/mapbox-events-android#442]
locationComponent is a null object reference and I can't get current lat/lng.

Root issue might be the error (which doesnt break the app):
Failed to obtain last location update.
Java.lang.exception: Last location unavailable.

This error is caught on Huawei P20 Lite with Android version 9. However, on my phones, Samsung A5 2017 and Samsung A8 2018 I had no such error and the location component works fine.

Log file to be posted in a minute

**Comment by alminkokasibovic** [comment]
E/Mbgl-LocationComponent: Failed to obtain last location update
    java.lang.Exception: Last location unavailable
        at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:40)
        at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
        at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1354)
        at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1173)
        at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1287)
        at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:506)
        at com.blum.MainActivity.enableLocationComponent(MainActivity.java:563)
        at com.blum.MainActivity.access$000(MainActivity.java:139)
        at com.blum.MainActivity$1.onStyleLoaded(MainActivity.java:795)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:855)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:212)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1264)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1035)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:386)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/Mbgl-MapChangeReceiver: Exception in onDidFinishLoadingStyle
    java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
        at com.blum.MainActivity.update_current_device_location(MainActivity.java:489)
        at com.blum.MainActivity.enableLocationComponent(MainActivity.java:599)
        at com.blum.MainActivity.access$000(MainActivity.java:139)
        at com.blum.MainActivity$1.onStyleLoaded(MainActivity.java:795)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:855)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:212)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1264)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1035)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:386)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 7342 (com.blum), pid 7342 (com.blum)
Disconnected from the target VM, address: 'localhost:8601', transport: 'socket'

**Comment by alminkokasibovic** [comment]
Key point in code:

The app breaks at the last line:

``private Location current_device_location;
``LocationComponent locationComponent;
``locationComponent = mapboxMap.getLocationComponent();
``current_device_location = locationComponent.getLastKnownLocation();
``latlng_current_location.setLatitude(current_device_location.getLatitude());

However, when I enable location component I get the error that the location is unavailable and therefore locationComponent is not initialized:

``locationComponent.setLocationComponentEnabled(true);

**Comment by alminkokasibovic** [comment]
build.gradle:

`/* Mapbox SDK */
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.5.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.9.0'`

**Comment by iamalminko** [comment]
The problem was that the gps location was disabled in android settings and that's why it was returning null pointer. It was just a coincidence that on Samsung it was enabled, and on Huawei it was disabled.

**Comment by Cloud9Clone** [comment]
A little question: When we use LocationComponent.setComponentEnabled(true) we create a Task for the current location, or we requestLocationUpdates and removeLocationUpdates?

**Comment by RicardoAguilarS** [comment]
> 

is there a way to catch/prevent this error when turning off the location setting?
