### ISSUE TITLE
🐞 Crash in background for Android 11

### ISSUE THREAD

**Issue by friendoye** [mapbox/mapbox-events-android#530]
**Context**
The issue is reported in https://github.com/mapbox/mapbox-search-android-examples/issues/25 and, according to crash logs, there might be something with `mapbox-android-telemetry`.

**Configuration**
 - SDK Version: v7.0.0
 - Android OS Version: Android 11
 - App: External app with Search SDK integration

**Steps to Reproduce**
There are no defined steps, but according to the customer:

> I have tried many many things but I cant reproduce the issue. I have noticed that app crashes 98% when it is in background. (ie. activity is not initialized)

**Expected**
Application doesn't crash in background.

**Logging**
Crash stacktrace:
```
Fatal Exception: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.mapbox.android.telemetry.MapboxTelemetryService$Binder
    at com.mapbox.android.telemetry.provider.MapboxTelemetryInitProvider$1.onServiceConnected(MapboxTelemetryInitProvider.java:38)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8506)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by friendoye** [comment]
Btw, it looks as if pretty similar issue was reported and fixed before: https://github.com/mapbox/mapbox-events-android/issues/207

No gonna say it is identical problem, but might be worth checking.
